Add supports for concurrent removeListener func
moleculer-go/goemitter pull request #2
Opened 2019-10-03 10:46 UTC by casskir

2019-10-07 21:04 UTC, slaterx commented
LGTM.

2019-10-10 06:48 UTC, pentateu requested changes

2019-10-10 06:48 UTC, pentateu commented on goemitter.go
> +
any particular reason to not use a defer self.mutex.Unlock() here ? instead of repeating it on each if / code branch ?

2019-10-10 06:48 UTC, pentateu commented on goemitter.go
> +			self.mutex.Unlock()
is this unlock() special ? does it need to be done before you call :
if !suppress {
				self.EmitSync("removeListener", []interface{}{event, callback})
			}


Ideally it should not be special.. and the simple patter of :
        self.mutex.Lock()
	defer self.mutex.Unlock()

is more desirable .. just like I'm here wondering why.. others will also in the future.

2019-10-12 05:30 UTC, casskir commented on goemitter.go
> +			self.mutex.Unlock()
If we call **self.EmitSync** without unlocking mutex then emitter will hang on the line https://github.com/moleculer-go/goemitter/blob/81f99c6b2583f8c4d6554a8c264d8f07c9e67940/goemitter.go#L120

2019-10-12 05:30 UTC, casskir commented on goemitter.go
> +
We must unlock mutex before call `emit`. If we will use defer here then we must control the mutex state in the defer function (we can't unlock mutex twice)

2019-10-13 10:22 UTC, merged